//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace creativo_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class creativoDBEntities : DbContext
    {
        public creativoDBEntities()
            : base("name=creativoDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMIN> ADMINS { get; set; }
        public virtual DbSet<CLIENTE> CLIENTES { get; set; }
        public virtual DbSet<EMPRENDIMIENTO> EMPRENDIMIENTOS { get; set; }
        public virtual DbSet<PEDIDO> PEDIDOS { get; set; }
        public virtual DbSet<PREGUNTA> PREGUNTAS { get; set; }
        public virtual DbSet<REPARTIDOR> REPARTIDORES { get; set; }
        public virtual DbSet<TALLER> TALLERES { get; set; }
        public virtual DbSet<TALLER_FOTOS> TALLER_FOTOS { get; set; }
        public virtual DbSet<ROL> ROLES { get; set; }
    }
}
