//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace creativo_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPRENDIMIENTO
    {
        public int IdEmprendimiento { get; set; }
        public string Usuario { get; set; }
        public string Pass { get; set; }
        public string Tipo { get; set; }
        public string Nombre { get; set; }
        public string Correo { get; set; }
        public string Sinpe { get; set; }
        public string Telefono { get; set; }
        public string Provincia { get; set; }
        public string Canton { get; set; }
        public string Distrito { get; set; }
        public string Estado { get; set; }
    }
}
