//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace creativo_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entrepreneurship_Admins
    {
        public int IdEntrepreneurship { get; set; }
        public int IdClient { get; set; }
        public string state { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Entrepreneurship Entrepreneurship { get; set; }
    }
}
