//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace creativo_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO
    {
        public int IdPedido { get; set; }
        public string Direccion { get; set; }
        public string Estado { get; set; }
        public Nullable<int> IdRepartidor { get; set; }
        public Nullable<int> IdCliente { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual REPARTIDOR REPARTIDOR { get; set; }
    }
}
